@startuml TOBE_CinemaAbyss_container

title TOBE CinemaAbyss container diagramm

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml



Person(depositManagerBackOffice, "Менеджер депозитов бек офиса", "Согласовывает ставку по депозиту для клиента")
Person(creditManagerBackOffice, "Менеджер кредитования бек офиса", "Проводит риск анализ, считает возможные ставки по кредитам и депозитам")
Person(managerFrontOffice, "Менеджер фронт офиса", "Обслуживает клиентов в офисе, формирует маркетинговые предложения на сайте")
Person(user, "User", "Клиент Банка")

System_Ext(callCenter, "Кол-центр")
System_Ext(mobileOperator, "Мобильный оператор")


System_Boundary(bankSystem, "Внутренняя система банка") {
    Container(abs, "АБС", "Delphi")
    ContainerDb(abs_db, "БД АБС", "Oracle")

    'Интернет банк
    Container(internetBankClient, "Интернет банк (клиентская часть)")
    Container(internetBank, "Интернет банк", "ASP.NET MVC 4.5 / .NET Framework 4.5")
    ContainerDb(internetBank_db, "БД Интернет банка", "MS SQL")
    'Сайт
    Container(webBankUI, "Сайт банка", "React.js")
    Container(webBankBE, "бек сайта банка", "PHP")
}

'Связи АБС
Rel(managerFrontOffice, abs, "Регистрация клиентов, получение предложений по депозитам и кредитам, открытие счетов и депозитов")
Rel(depositManagerBackOffice, abs,  "Получение ставок по депозитам")
Rel(creditManagerBackOffice, abs, "Расчет кредитного риска, расчет возможных ставок по депозиту")

BiRel(abs, abs_db, "сохранение, обновление данных")
Rel(abs, mobileOperator, "Отправка кода подтверждения клиенту")
Rel(callCenter, abs, "Данные по клиентам, заведение заявок")

'Связи интернет банка
Rel(user, internetBankClient, "управление счетами, платежи, открытие депозитов")
Rel(internetBankClient, internetBank, "Управление счетами, платежи, открытие депозита")
BiRel(internetBank, internetBank_db, "сохранение данных")
Rel(internetBank, abs_db, "управление счетами, платежи")

'Связи сайта
Rel(user, webBankUI, "просмотр ставок по депозитам, завдение заявок на депозит")
Rel(webBankUI, webBankBE, "Заявки на депозит, получение маркетинговых предложений", "HTTPS")
Rel(webBankBE, abs, "Заведение заявки на депозит", "HTTPS")

@enduml